name: trippo
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sliding_clipped_nav_bar: ^2.0.1
  flutter_bloc: ^8.0.0
  flutter_svg: ^1.0.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.4
  shared_preferences: ^2.0.11
  bot_toast: ^4.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/svg/

  
  fonts:
    - family: Sf-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
          style: normal

        - asset: assets/fonts/SF-Pro-Display-light.otf
          weight: 300
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 900
          style: normal


    - family: TrippoIcons
      fonts:
        - asset: assets/icons/TrippoIcons.ttf