name: trippo
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sliding_clipped_nav_bar: ^2.0.1
  flutter_bloc: ^8.0.0
  flutter_svg: ^1.0.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.4
  shared_preferences: ^2.0.11
  bot_toast: ^4.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/svg/

  
  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
    
    - family: TrippoIcons
      fonts:
        - asset: assets\icon\TrippoIcons.ttf